name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: hugoh/gh-workflows/setup@c95078d6578bc039453fc9c865a0bc651dc00982 # v1.40.7
      - run: uv sync
      - run: uv run pytest
      - uses: hugoh/gh-workflows/hk-check@c95078d6578bc039453fc9c865a0bc651dc00982 # v1.40.7
