name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: hugoh/gh-workflows/setup@fc872ebc6ac6bb28fa73a2e83f9f354faad9b5b7 # v1.40.6
      - run: uv sync
      - run: uv run pytest
      - uses: hugoh/gh-workflows/hk-check@fc872ebc6ac6bb28fa73a2e83f9f354faad9b5b7 # v1.40.6
