name: hk

permissions:
  contents: read
  packages: read
  statuses: write

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: hugoh/gh-workflows/setup@fe2707057b8da8fab2460fc1f0e816561fa8a958 # v1.3.0
      - run: uv sync
      - run: uv run pytest
      - uses: hugoh/gh-workflows/hk-check@fe2707057b8da8fab2460fc1f0e816561fa8a958 # v1.3.0
